<?php
function hide_show_password_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {

    case 'user_login_block':
    case 'user_login':

      $this_module = drupal_get_path('module', 'hide_show_password');

      $css_path = $this_module . '/css';
      $js_path = $this_module . '/js';
      $bower_path = $js_path . '/bower_components';

      drupal_add_css($css_path . '/hideShowPassword.css');
      drupal_add_js($js_path . '/main.js', array('scope' => 'footer', 'weight' => 100));
      drupal_add_js($bower_path . '/hideShowPassword/hideShowPassword.min.js');
      break;

    default:
      //
      break;
  }
}